/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.mgmt;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertTrue(true);
    }
}
